// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAatFFFrfTYsqsEJXw8ivL7RT8MhGJ5fA',
    appId: '1:353128007543:web:8d80969efe598bdf660372',
    messagingSenderId: '353128007543',
    projectId: 'rapellemoi-a6de8',
    authDomain: 'rapellemoi-a6de8.firebaseapp.com',
    storageBucket: 'rapellemoi-a6de8.firebasestorage.app',
    measurementId: 'G-MCZZXM7TKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5umZuCdMmG9Wm2QfMiornvrBIMI28UZc',
    appId: '1:353128007543:android:a05300efef7e808a660372',
    messagingSenderId: '353128007543',
    projectId: 'rapellemoi-a6de8',
    storageBucket: 'rapellemoi-a6de8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1H8RJJE2YK60K9DxOWStXBlc-VHs-kY8',
    appId: '1:353128007543:ios:66528751b09f7c4d660372',
    messagingSenderId: '353128007543',
    projectId: 'rapellemoi-a6de8',
    storageBucket: 'rapellemoi-a6de8.firebasestorage.app',
    iosBundleId: 'co.penseeexprimee.rappellemoi',
  );
}
